### ISSUE TITLE
Having an error with loading css of this lib in Next

### ISSUE THREAD

**Issue by SpaceHolderdJs** [zheeeng/react-device-frameset#11]
Tried differently, but no luck. I am sure it`s possible to solve, any ideas ?

<img width="801" alt="image" src="https://github.com/zheeeng/react-device-frameset/assets/62031924/753a0010-8b5e-432d-99b4-823ed487db38">

P.S this is how I used it in the component

<img width="590" alt="image" src="https://github.com/zheeeng/react-device-frameset/assets/62031924/8c829f78-f530-437f-9d63-569496e7a8c8">

**Comment by SpaceHolderdJs** [comment]
And for sure there is all needed files installed in node_module via yarn

**Comment by SpaceHolderdJs** [comment]
```
import React, { PropsWithChildren, FC } from "react";
import { DeviceFrameset } from "react-device-frameset";
import "react-device-frameset/dist/styles/marvel-devices.min.css";

interface Props extends PropsWithChildren {
    device: string;
}

export const DeviceFrame: FC<Props> = ({ children, device }) => {
    return (
        <div>
            <DeviceFrameset
                style={{ width: "300px", height: "400px" }}
                device={device as never}
            >
                {children}
            </DeviceFrameset>
        </div>
    );
};

```

**Comment by zheeeng** [comment]
try `import 'react-device-frameset/styles/marvel-devices.min.css'`?

**Comment by SpaceHolderdJs** [comment]
Perfect, thanks!
