### ISSUE TITLE
Documentation on npmjs.com is out of date. 

### ISSUE THREAD

**Issue by jeffharrington** [zheeeng/react-device-frameset#13]
Just a heads up that the [NPM documentation for react-device-frameset](https://www.npmjs.com/package/react-device-frameset)  is out of date. 

On that site, it says to use the following import for the CSS: 
```jsx
import 'react-device-frameset/dist/styles/marvel-devices.min.css'
```

However, the Github documentation notes a different (and correct) import of:
```jsx
import 'react-device-frameset/styles/marvel-devices.min.css';
```

**Comment by zheeeng** [comment]
Thx! v1.3.3 released.
