### ISSUE TITLE
New iPhone models

### ISSUE THREAD

**Issue by pinktonio** [zheeeng/react-device-frameset#6]
Great library, thank you!
Will you also add the latest iPhone models in the near future?

**Comment by zheeeng** [comment]
It's based on http://marvelapp.github.io/devices.css/, if they are going to update I'll follow up.

**Comment by pinktonio** [comment]
Cool thanks. Btw I'm getting an error on any import: "default condition should be last one"

**Comment by zheeeng** [comment]
Is there a repro for this issue?

**Comment by pinktonio** [comment]
No unfortunately not. But happens in my newest next.js project.

**Comment by zheeeng** [comment]
Seems something related to next.js.
I'm using a common usage of exports filed, but I'd make some changes to fit next's rules.

reference: https://fixjserror.com/next/default-condition-should-be-last-one/

**Comment by zheeeng** [comment]
A new version v1.3.2 was released for your issue, feedback is welcome.

**Comment by pinktonio** [comment]
Yeah thanks. That issue is resolved but now i get an error on the css import: Module not found: Can't resolve 'react-device-frameset/dist/styles/marvel-devices.min.css'

**Comment by zheeeng** [comment]
My bad, you can import the stylesheet through `react-device-frameset/styles/marvel-devices.min.css`(without `dist`), becoz we added the node's conditional exports feature, which is largely applicated in major dev scaffolds.

**Comment by pinktonio** [comment]
Thanks, now it's working!
