### ISSUE TITLE
i try to use it but got an errors 

### ISSUE THREAD

**Issue by zaherkassem** [zheeeng/react-device-frameset#9]
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 210:29-40
Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 221:28-39
Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 230:34-45
Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 289:29-41
Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 296:33-45
Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 306:34-46
Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 225:2-11
Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 319:2-12
Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 414:2-12
Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 432:2-12
Can't import the named export 'useEffect' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 146:16-23
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 207:22-30
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 209:29-37
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 218:50-58
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 219:21-29
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 229:29-37
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 235:30-38
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 283:22-30
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 285:29-37
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 302:50-58
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 303:21-29
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 305:29-37
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 311:30-38
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 404:16-24
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 409:20-28
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 410:22-30
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 411:25-33
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 208:38-46
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 217:34-42
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 220:44-52
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 228:40-48
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 284:38-47
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 295:42-51
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 304:40-49
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 400:37-46
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 401:55-64
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 402:36-45
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 403:44-53
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
ERROR in ../node_modules/react-device-frameset/dist/index.mjs 408:39-48
Can't import the named export 'useState' from non EcmaScript module (only default export is available)

**Comment by zheeeng** [comment]
It seems you need to configure your webpack to add rule:

```js
{
        include: /node_modules/,
        test: /\.mjs$/,
        type: 'javascript/auto'
},
```
